print("Welcome to Karan's Crappy Calculator")
x = input("Choose the first number" )
int(x)
y = input("Choose the second number" )
int(y)
sum = int(x) + int(y)
print("the sum of " + str(x) + " and " + str(y) + " is: " + str(sum))
print("the difference of " + str(x) + " and " + str(y) + " is: " + str(int(x) - int(y)))
print("the product of " + str(x) + " and " + str(y) + " is: " + str(int(x) * int(y)))
print("the division of " + str(x) + " and " + str(y) + " is: " + str(int(x) / int(y)))
print("the power of " + str(x) + " and " + str(y) + " is: " + str(int(x) ** int(y)))
print("the square root of " + str(x) + " is: " + str(int(x) ** (1/2)))
print("the square root of " + str(y) + " is: " + str(int(y) ** (1/2)))